export const STRIPE_PRICES = {
  PRO_MONTHLY: process.env.NEXT_PUBLIC_STRIPE_PRICE_PRO_MONTHLY || "price_1Tw3LtC8RNlc853MrrcSs283",
  PRO_YEARLY: process.env.NEXT_PUBLIC_STRIPE_PRICE_PRO_YEARLY || "price_1Tw3hPC8RNlc853MpiOM6xZR",
  AGENCY_MONTHLY: process.env.NEXT_PUBLIC_STRIPE_PRICE_AGENCY_MONTHLY || "price_1Tw3MhC8RNlc853MOFMwLf29",
  AGENCY_YEARLY: process.env.NEXT_PUBLIC_STRIPE_PRICE_AGENCY_YEARLY || "price_1Tw3kcC8RNlc853MZgdWsTpo",
};
